# Generated by Django 4.2.18 on 2025-04-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkslibrary',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
