# Generated by Django 4.2.18 on 2025-04-02 05:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_linkslibrary_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkslibrary',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
