# Generated by Django 4.2.18 on 2025-04-02 05:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_linkslibrary_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkslibrary',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
