# Generated by Django 4.2.18 on 2025-04-02 05:47

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_linkslibrary_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkslibrary',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
