# Generated by Django 4.2.18 on 2025-04-02 06:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_linkslibrary_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkslibrary',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
