# Generated by Django 4.2.18 on 2025-04-02 07:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_linkslibrary_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkslibrary',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
