# Generated by Django 4.2.18 on 2025-04-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_linkslibrary_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkslibrary',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
