# Generated by Django 4.2.18 on 2025-04-05 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_linkslibrary_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkslibrary',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
