# Generated by Django 4.2.18 on 2025-04-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_linkslibrary_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkslibrary',
            name='liked_by',
        ),
    ]
