# Generated by Django 4.2.18 on 2025-04-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_comment_liked_by_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkslibrary',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
