# Generated by Django 4.2.18 on 2025-04-13 06:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0015_alter_linkslibrary_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinksLibrary',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
    ]
