# Generated by Django 4.2.18 on 2025-04-15 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0018_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating_by',
            field=models.ManyToManyField(related_name='rating_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
