# Generated by Django 4.2.18 on 2025-04-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_post_rating_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating_what',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
