# Generated by Django 4.2.18 on 2025-04-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating_what',
            field=models.IntegerField(default=5),
        ),
    ]
