# Generated by Django 4.2.18 on 2025-04-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_post_rating_alter_post_rating_what'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating_what',
            field=models.IntegerField(default='none'),
        ),
    ]
