# Generated by Django 4.2.18 on 2025-04-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat_img',
            field=models.CharField(default='Без темы', max_length=255),
        ),
    ]
