# Generated by Django 4.2.18 on 2025-04-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_post_cat_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cat_img',
            new_name='cut_img',
        ),
        migrations.AddField(
            model_name='post',
            name='wrapp_img',
            field=models.ImageField(null=True, upload_to='post_img/'),
        ),
    ]
