# Generated by Django 4.2.18 on 2025-04-23 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0030_rename_cat_img_post_cut_img_post_wrapp_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['status']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(default='none', related_name='likedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
