# Generated by Django 4.2.18 on 2025-04-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_alter_post_options_alter_comment_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
