# Generated by Django 4.2.18 on 2025-04-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profile_pics/default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
