# Generated by Django 4.2.18 on 2025-05-02 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscription_follower_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subscription',
            name='followers',
            field=models.ManyToManyField(blank=True, default=0, null=True, related_name='my_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='followings',
            field=models.ManyToManyField(blank=True, default=0, null=True, related_name='my_follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='following',
        ),
    ]
