# Generated by Django 4.2.18 on 2025-05-02 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_subscription_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='my_follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='my_followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
