# Generated by Django 4.2.18 on 2025-05-09 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
