# Generated by Django 4.2.18 on 2025-05-09 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notifications_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 14, 41, 54, 810026, tzinfo=datetime.timezone.utc)),
        ),
    ]
