# Generated by Django 4.2.18 on 2025-05-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notifications_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='expired_at',
        ),
    ]
