# Generated by Django 4.2.18 on 2025-10-01 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_notifications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='actor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
