# Generated by Django 4.2.18 on 2025-10-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_notifications_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='link',
            field=models.TextField(default='none', max_length=500),
        ),
    ]
