# Generated by Django 4.2.18 on 2025-10-07 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_notifications_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='my_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
