# Generated by Django 4.2.18 on 2025-11-22 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='Nothing', max_length=1000, null=True)),
                ('cat_title', models.CharField(max_length=255, unique=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('wrapp_img', models.ImageField(blank=True, null=True, upload_to='post_img/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_type', models.CharField(max_length=100)),
                ('status', models.TextField(choices=[('draft', 'Одобрено'), ('published', 'На рассмотрении'), ('canceled', 'Отклонено')], default='published')),
                ('views_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
