# Generated by Django 4.2.18 on 2025-05-12 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark_user',
            field=models.ManyToManyField(related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
