# Generated by Django 4.2.18 on 2025-05-22 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='category_follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='category_followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
