# Generated by Django 4.2.18 on 2025-05-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_category_followers_category_followings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='followings',
        ),
    ]
