# Generated by Django 4.2.18 on 2025-07-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_rename_name_category_cat_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked_by',
            new_name='liked_by',
        ),
    ]
