# Generated by Django 4.2.18 on 2025-07-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_rename_liked_by_post_liked_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked_by',
            new_name='liked_by',
        ),
    ]
