# Generated by Django 4.2.18 on 2025-08-31 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0015_alter_post_bookmark_user_alter_post_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='replycomment',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='reply_liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
