# Generated by Django 4.2.18 on 2025-08-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_comment_liked_by_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='wrapp_img',
            field=models.ImageField(blank=True, null=True, upload_to='post_img/'),
        ),
    ]
