# Generated by Django 4.2.18 on 2025-09-20 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0017_alter_post_title_alter_post_wrapp_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarkedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
