# Generated by Django 4.2.18 on 2025-09-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_comment_bookmarked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.TextField(choices=[('post', 'Пост'), ('article', 'Статья'), ('news', 'Новость')], default='type'),
        ),
    ]
