# Generated by Django 4.2.18 on 2025-09-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.TextField(choices=[('post', 'Пост'), ('article', 'Статья'), ('news', 'Новость')], default='post'),
        ),
    ]
