# Generated by Django 4.2.18 on 2025-10-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
