# Generated by Django 4.2.18 on 2025-10-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_category_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply_count',
        ),
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
