# Generated by Django 4.2.18 on 2025-11-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_remove_comment_reply_count_delete_replycomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cut_img',
        ),
    ]
